resource_group_name = 
vnet                = 
subnet              = 
location            = 
Machine_Name        = 
Machine_size        = 
Machine_Image_name  = 
NIC_Name            = 
#Network_Security_Group = 
Storage_Account_Tier = 
Disk_Name            = 
User_Name            = 
Password             = 
availability_set     = 
recovery_services_protection_policy_id = 
recovery_services_vault_name = "
